--
-- PostgreSQL database dump
--

\restrict qIvubUXJHCGtihtDnM3CxDNrAA3c6XQAtm6UkH7bVHFuLkjuVOBwymQn5RxcsRU

-- Dumped from database version 18.4 (Debian 18.4-1.pgdg13+1)
-- Dumped by pg_dump version 18.4 (Debian 18.4-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: achievements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.achievements (
    achievement_id integer NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    difficulty character varying(50) NOT NULL,
    reward_money numeric(10,2) DEFAULT 0.00
);


ALTER TABLE public.achievements OWNER TO postgres;

--
-- Name: achievements_achievement_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.achievements ALTER COLUMN achievement_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.achievements_achievement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: active_accepted_challenges; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.active_accepted_challenges (
    user_id integer NOT NULL,
    challenge_id integer NOT NULL,
    code_state text,
    started_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.active_accepted_challenges OWNER TO postgres;

--
-- Name: advanced_validation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.advanced_validation (
    id integer NOT NULL,
    question_text text NOT NULL,
    correct_answer character varying(500) NOT NULL
);


ALTER TABLE public.advanced_validation OWNER TO postgres;

--
-- Name: advanced_validation_choices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.advanced_validation_choices (
    id integer NOT NULL,
    question_id integer NOT NULL,
    choice_text character varying(500) NOT NULL
);


ALTER TABLE public.advanced_validation_choices OWNER TO postgres;

--
-- Name: advanced_validation_choices_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.advanced_validation_choices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.advanced_validation_choices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: advanced_validation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.advanced_validation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.advanced_validation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assessment_choices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.assessment_choices (
    id integer NOT NULL,
    question_id integer,
    choice_text text,
    "order" integer
);


ALTER TABLE public.assessment_choices OWNER TO postgres;

--
-- Name: assessment_choices_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.assessment_choices_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.assessment_choices_id_seq OWNER TO postgres;

--
-- Name: assessment_choices_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.assessment_choices_id_seq OWNED BY public.assessment_choices.id;


--
-- Name: assessment_questions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.assessment_questions (
    id integer NOT NULL,
    level_value integer,
    question_text text,
    question_type character varying(20),
    correct_answer text
);


ALTER TABLE public.assessment_questions OWNER TO postgres;

--
-- Name: assessment_questions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.assessment_questions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.assessment_questions_id_seq OWNER TO postgres;

--
-- Name: assessment_questions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.assessment_questions_id_seq OWNED BY public.assessment_questions.id;


--
-- Name: cosmetics; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cosmetics (
    cosmetic_id integer NOT NULL,
    name character varying(200) NOT NULL,
    type character varying(50) NOT NULL,
    price integer DEFAULT 0 NOT NULL,
    asset_url character varying(500)
);


ALTER TABLE public.cosmetics OWNER TO postgres;

--
-- Name: cosmetics_cosmetic_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cosmetics ALTER COLUMN cosmetic_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cosmetics_cosmetic_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: email_verifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.email_verifications (
    id integer NOT NULL,
    user_id integer NOT NULL,
    token character varying(255) NOT NULL,
    expires_at timestamp without time zone,
    verified_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.email_verifications OWNER TO postgres;

--
-- Name: email_verifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.email_verifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.email_verifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exercise_submissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exercise_submissions (
    submission_id integer NOT NULL,
    user_id integer,
    exercise_id integer,
    submitted_code text NOT NULL,
    is_passed boolean DEFAULT false,
    score integer DEFAULT 0,
    execution_time_ms integer,
    error_message text,
    submitted_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.exercise_submissions OWNER TO postgres;

--
-- Name: exercise_submissions_submission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.exercise_submissions_submission_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.exercise_submissions_submission_id_seq OWNER TO postgres;

--
-- Name: exercise_submissions_submission_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.exercise_submissions_submission_id_seq OWNED BY public.exercise_submissions.submission_id;


--
-- Name: exercises; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exercises (
    exercise_id integer NOT NULL,
    lesson_id integer,
    title character varying(100),
    description text,
    starter_code text,
    solution_code text,
    test_cases jsonb,
    xp_reward integer DEFAULT 10,
    currency_reward integer DEFAULT 5
);


ALTER TABLE public.exercises OWNER TO postgres;

--
-- Name: exercises_exercise_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.exercises_exercise_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.exercises_exercise_id_seq OWNER TO postgres;

--
-- Name: exercises_exercise_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.exercises_exercise_id_seq OWNED BY public.exercises.exercise_id;


--
-- Name: learning_ai_tasks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.learning_ai_tasks (
    task_id integer NOT NULL,
    user_id integer NOT NULL,
    mode character varying(20) NOT NULL,
    title character varying(255) NOT NULL,
    section_label character varying(100),
    subtitle character varying(100),
    accent character varying(20),
    instructions_json text NOT NULL,
    example_input text,
    example_output text,
    starter_code text NOT NULL,
    test_cases_json text NOT NULL,
    reward_xp integer DEFAULT 100 NOT NULL,
    reward_coins integer DEFAULT 20 NOT NULL,
    rerolls_used integer DEFAULT 0 NOT NULL,
    max_rerolls integer DEFAULT 3 NOT NULL,
    status character varying(50) DEFAULT 'ACTIVE'::character varying NOT NULL,
    ai_payload text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    completed_at timestamp without time zone
);


ALTER TABLE public.learning_ai_tasks OWNER TO postgres;

--
-- Name: learning_ai_tasks_task_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.learning_ai_tasks ALTER COLUMN task_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.learning_ai_tasks_task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lesson_quizzes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.lesson_quizzes (
    quiz_id integer NOT NULL,
    lesson_id integer NOT NULL,
    quiz_type character varying(10) NOT NULL
);


ALTER TABLE public.lesson_quizzes OWNER TO postgres;

--
-- Name: lesson_quizzes_quiz_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.lesson_quizzes_quiz_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.lesson_quizzes_quiz_id_seq OWNER TO postgres;

--
-- Name: lesson_quizzes_quiz_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.lesson_quizzes_quiz_id_seq OWNED BY public.lesson_quizzes.quiz_id;


--
-- Name: lesson_slides; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.lesson_slides (
    slide_id integer NOT NULL,
    lesson_id integer NOT NULL,
    slide_order integer NOT NULL,
    slide_title character varying(255),
    slide_content text,
    slide_src character varying(255),
    slide_type character varying(20) DEFAULT 'image'::character varying NOT NULL
);


ALTER TABLE public.lesson_slides OWNER TO postgres;

--
-- Name: lesson_slides_slide_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.lesson_slides_slide_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.lesson_slides_slide_id_seq OWNER TO postgres;

--
-- Name: lesson_slides_slide_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.lesson_slides_slide_id_seq OWNED BY public.lesson_slides.slide_id;


--
-- Name: lessons; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.lessons (
    lesson_id integer NOT NULL,
    module_id integer,
    title character varying(100) NOT NULL,
    content text,
    order_index integer NOT NULL,
    required_level integer DEFAULT 1,
    description text
);


ALTER TABLE public.lessons OWNER TO postgres;

--
-- Name: lessons_lesson_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.lessons_lesson_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.lessons_lesson_id_seq OWNER TO postgres;

--
-- Name: lessons_lesson_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.lessons_lesson_id_seq OWNED BY public.lessons.lesson_id;


--
-- Name: level_config; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.level_config (
    id integer NOT NULL,
    q_id integer,
    title character varying(50),
    level_value integer,
    "order" integer
);


ALTER TABLE public.level_config OWNER TO postgres;

--
-- Name: level_config_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.level_config_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.level_config_id_seq OWNER TO postgres;

--
-- Name: level_config_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.level_config_id_seq OWNED BY public.level_config.id;


--
-- Name: modules; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.modules (
    module_id integer NOT NULL,
    title character varying(100) NOT NULL,
    description text,
    order_index integer NOT NULL,
    is_locked boolean DEFAULT true,
    required_level integer DEFAULT 1
);


ALTER TABLE public.modules OWNER TO postgres;

--
-- Name: modules_module_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.modules_module_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.modules_module_id_seq OWNER TO postgres;

--
-- Name: modules_module_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.modules_module_id_seq OWNED BY public.modules.module_id;


--
-- Name: multiplayer_challenges; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.multiplayer_challenges (
    challenge_id integer NOT NULL,
    title character varying(200) NOT NULL,
    description text NOT NULL,
    difficulty character varying(50) DEFAULT 'Easy'::character varying NOT NULL,
    reward integer DEFAULT 500 NOT NULL,
    time_limit integer DEFAULT 300 NOT NULL,
    test_cases jsonb NOT NULL,
    created_by integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    is_test integer DEFAULT 0,
    expires_at timestamp without time zone DEFAULT (CURRENT_TIMESTAMP + '7 days'::interval)
);


ALTER TABLE public.multiplayer_challenges OWNER TO postgres;

--
-- Name: multiplayer_challenges_challenge_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.multiplayer_challenges ALTER COLUMN challenge_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.multiplayer_challenges_challenge_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: multiplayer_sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.multiplayer_sessions (
    session_id character varying(100) NOT NULL,
    mode character varying(50) NOT NULL,
    status character varying(50) DEFAULT 'waiting'::character varying NOT NULL,
    current_round integer DEFAULT 1 NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.multiplayer_sessions OWNER TO postgres;

--
-- Name: multiplayer_submissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.multiplayer_submissions (
    submission_id integer NOT NULL,
    session_id character varying(100),
    user_id integer,
    challenge_id integer,
    code text NOT NULL,
    score integer DEFAULT 0 NOT NULL,
    passed_cases integer DEFAULT 0 NOT NULL,
    total_cases integer DEFAULT 0 NOT NULL,
    ai_feedback jsonb,
    submitted_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    efficiency_ms integer DEFAULT 0
);


ALTER TABLE public.multiplayer_submissions OWNER TO postgres;

--
-- Name: multiplayer_submissions_submission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.multiplayer_submissions ALTER COLUMN submission_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.multiplayer_submissions_submission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: music_tracks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.music_tracks (
    track_id integer NOT NULL,
    track_name character varying(100) NOT NULL,
    file_path character varying(255) NOT NULL,
    is_default integer DEFAULT 0
);


ALTER TABLE public.music_tracks OWNER TO postgres;

--
-- Name: music_tracks_track_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.music_tracks ALTER COLUMN track_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.music_tracks_track_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: question_choices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.question_choices (
    choice_id integer NOT NULL,
    question_id integer NOT NULL,
    choice_text character varying(255) NOT NULL
);


ALTER TABLE public.question_choices OWNER TO postgres;

--
-- Name: question_choices_choice_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.question_choices_choice_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.question_choices_choice_id_seq OWNER TO postgres;

--
-- Name: question_choices_choice_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.question_choices_choice_id_seq OWNED BY public.question_choices.choice_id;


--
-- Name: quiz_questions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quiz_questions (
    question_id integer NOT NULL,
    quiz_id integer NOT NULL,
    question_order integer NOT NULL,
    question_text text NOT NULL,
    question_type character varying(10) NOT NULL,
    correct_answer character varying(255) NOT NULL
);


ALTER TABLE public.quiz_questions OWNER TO postgres;

--
-- Name: quiz_questions_question_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.quiz_questions_question_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.quiz_questions_question_id_seq OWNER TO postgres;

--
-- Name: quiz_questions_question_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.quiz_questions_question_id_seq OWNED BY public.quiz_questions.question_id;


--
-- Name: session_players; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.session_players (
    session_id character varying(100) NOT NULL,
    user_id integer NOT NULL,
    money_balance integer DEFAULT 0 NOT NULL,
    is_survived integer DEFAULT 1 NOT NULL,
    score integer DEFAULT 0 NOT NULL,
    status character varying(50) DEFAULT 'joined'::character varying NOT NULL
);


ALTER TABLE public.session_players OWNER TO postgres;

--
-- Name: shop_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shop_items (
    item_id integer NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    item_type character varying(50) NOT NULL,
    price integer DEFAULT 0 NOT NULL,
    asset_url character varying(255),
    preview_image character varying(255),
    is_active boolean DEFAULT true,
    effects jsonb DEFAULT '[]'::jsonb
);


ALTER TABLE public.shop_items OWNER TO postgres;

--
-- Name: shop_items_item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.shop_items_item_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.shop_items_item_id_seq OWNER TO postgres;

--
-- Name: shop_items_item_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.shop_items_item_id_seq OWNED BY public.shop_items.item_id;


--
-- Name: survey_options; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.survey_options (
    id integer NOT NULL,
    question_id integer,
    option_text character varying(100) NOT NULL,
    option_description text,
    "order" integer DEFAULT 0
);


ALTER TABLE public.survey_options OWNER TO postgres;

--
-- Name: survey_options_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.survey_options_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.survey_options_id_seq OWNER TO postgres;

--
-- Name: survey_options_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.survey_options_id_seq OWNED BY public.survey_options.id;


--
-- Name: survey_questions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.survey_questions (
    id integer NOT NULL,
    title text NOT NULL,
    image character varying(255),
    description text
);


ALTER TABLE public.survey_questions OWNER TO postgres;

--
-- Name: survey_questions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.survey_questions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.survey_questions_id_seq OWNER TO postgres;

--
-- Name: survey_questions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.survey_questions_id_seq OWNED BY public.survey_questions.id;


--
-- Name: user_achievements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_achievements (
    id integer NOT NULL,
    user_id integer NOT NULL,
    achievement_id integer NOT NULL,
    unlocked_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.user_achievements OWNER TO postgres;

--
-- Name: user_achievements_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_achievements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_achievements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_cosmetics; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_cosmetics (
    user_id integer NOT NULL,
    cosmetic_id integer NOT NULL,
    is_equipped integer DEFAULT 0 NOT NULL,
    purchased_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.user_cosmetics OWNER TO postgres;

--
-- Name: user_mailbox; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_mailbox (
    mail_id integer NOT NULL,
    user_id integer,
    title character varying(255) NOT NULL,
    content text NOT NULL,
    attachment_coins integer DEFAULT 0,
    is_read integer DEFAULT 0,
    is_claimed integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.user_mailbox OWNER TO postgres;

--
-- Name: user_mailbox_mail_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_mailbox ALTER COLUMN mail_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_mailbox_mail_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_missions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_missions (
    user_mission_id integer NOT NULL,
    user_id integer,
    email_id integer,
    status character varying(20) DEFAULT 'pending'::character varying,
    accepted_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    completed_at timestamp without time zone
);


ALTER TABLE public.user_missions OWNER TO postgres;

--
-- Name: user_missions_user_mission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.user_missions_user_mission_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.user_missions_user_mission_id_seq OWNER TO postgres;

--
-- Name: user_missions_user_mission_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.user_missions_user_mission_id_seq OWNED BY public.user_missions.user_mission_id;


--
-- Name: user_progress; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_progress (
    progress_id integer NOT NULL,
    user_id integer,
    lesson_id integer,
    status character varying(20) DEFAULT 'locked'::character varying,
    score integer DEFAULT 0,
    completed_at timestamp without time zone
);


ALTER TABLE public.user_progress OWNER TO postgres;

--
-- Name: user_progress_progress_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.user_progress_progress_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.user_progress_progress_id_seq OWNER TO postgres;

--
-- Name: user_progress_progress_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.user_progress_progress_id_seq OWNED BY public.user_progress.progress_id;


--
-- Name: user_quiz_attempts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_quiz_attempts (
    attempt_id integer NOT NULL,
    user_id integer,
    lesson_id integer,
    quiz_type character varying(10),
    score integer NOT NULL,
    total_questions integer NOT NULL,
    passed boolean NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_quiz_attempts_quiz_type_check CHECK (((quiz_type)::text = ANY (ARRAY[('pre'::character varying)::text, ('post'::character varying)::text])))
);


ALTER TABLE public.user_quiz_attempts OWNER TO postgres;

--
-- Name: user_quiz_attempts_attempt_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.user_quiz_attempts_attempt_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.user_quiz_attempts_attempt_id_seq OWNER TO postgres;

--
-- Name: user_quiz_attempts_attempt_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.user_quiz_attempts_attempt_id_seq OWNED BY public.user_quiz_attempts.attempt_id;


--
-- Name: user_survey_responses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_survey_responses (
    response_id integer NOT NULL,
    user_id integer,
    question_id integer,
    selected_option character varying(255),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.user_survey_responses OWNER TO postgres;

--
-- Name: user_survey_responses_response_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.user_survey_responses_response_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.user_survey_responses_response_id_seq OWNER TO postgres;

--
-- Name: user_survey_responses_response_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.user_survey_responses_response_id_seq OWNED BY public.user_survey_responses.response_id;


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    user_id integer NOT NULL,
    username character varying(50) NOT NULL,
    email character varying(100),
    password_hash character varying(255) NOT NULL,
    role character varying(20) DEFAULT 'student'::character varying,
    level integer DEFAULT 1,
    xp integer DEFAULT 0,
    virtual_currency integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    reset_token character varying(255),
    reset_token_expiry timestamp without time zone,
    is_deleted boolean DEFAULT false,
    deleted_at timestamp without time zone,
    is_banned boolean DEFAULT false,
    ban_until timestamp without time zone,
    reputation integer DEFAULT 10,
    equipped_theme_id integer,
    equipped_mouse_effect_id integer,
    equipped_profile_frame_id integer,
    avatar_url character varying(255),
    bio character varying(500)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.users_user_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_user_id_seq OWNER TO postgres;

--
-- Name: users_user_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.users_user_id_seq OWNED BY public.users.user_id;


--
-- Name: virtual_emails; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.virtual_emails (
    email_id integer NOT NULL,
    sender_name character varying(100),
    subject character varying(200),
    body_content text,
    related_exercise_id integer,
    difficulty_level character varying(20),
    sent_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.virtual_emails OWNER TO postgres;

--
-- Name: virtual_emails_email_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.virtual_emails_email_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.virtual_emails_email_id_seq OWNER TO postgres;

--
-- Name: virtual_emails_email_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.virtual_emails_email_id_seq OWNED BY public.virtual_emails.email_id;


--
-- Name: assessment_choices id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assessment_choices ALTER COLUMN id SET DEFAULT nextval('public.assessment_choices_id_seq'::regclass);


--
-- Name: assessment_questions id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assessment_questions ALTER COLUMN id SET DEFAULT nextval('public.assessment_questions_id_seq'::regclass);


--
-- Name: exercise_submissions submission_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercise_submissions ALTER COLUMN submission_id SET DEFAULT nextval('public.exercise_submissions_submission_id_seq'::regclass);


--
-- Name: exercises exercise_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercises ALTER COLUMN exercise_id SET DEFAULT nextval('public.exercises_exercise_id_seq'::regclass);


--
-- Name: lesson_quizzes quiz_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lesson_quizzes ALTER COLUMN quiz_id SET DEFAULT nextval('public.lesson_quizzes_quiz_id_seq'::regclass);


--
-- Name: lesson_slides slide_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lesson_slides ALTER COLUMN slide_id SET DEFAULT nextval('public.lesson_slides_slide_id_seq'::regclass);


--
-- Name: lessons lesson_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lessons ALTER COLUMN lesson_id SET DEFAULT nextval('public.lessons_lesson_id_seq'::regclass);


--
-- Name: level_config id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.level_config ALTER COLUMN id SET DEFAULT nextval('public.level_config_id_seq'::regclass);


--
-- Name: modules module_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.modules ALTER COLUMN module_id SET DEFAULT nextval('public.modules_module_id_seq'::regclass);


--
-- Name: question_choices choice_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.question_choices ALTER COLUMN choice_id SET DEFAULT nextval('public.question_choices_choice_id_seq'::regclass);


--
-- Name: quiz_questions question_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_questions ALTER COLUMN question_id SET DEFAULT nextval('public.quiz_questions_question_id_seq'::regclass);


--
-- Name: shop_items item_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_items ALTER COLUMN item_id SET DEFAULT nextval('public.shop_items_item_id_seq'::regclass);


--
-- Name: survey_options id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.survey_options ALTER COLUMN id SET DEFAULT nextval('public.survey_options_id_seq'::regclass);


--
-- Name: survey_questions id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.survey_questions ALTER COLUMN id SET DEFAULT nextval('public.survey_questions_id_seq'::regclass);


--
-- Name: user_missions user_mission_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_missions ALTER COLUMN user_mission_id SET DEFAULT nextval('public.user_missions_user_mission_id_seq'::regclass);


--
-- Name: user_progress progress_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_progress ALTER COLUMN progress_id SET DEFAULT nextval('public.user_progress_progress_id_seq'::regclass);


--
-- Name: user_quiz_attempts attempt_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_quiz_attempts ALTER COLUMN attempt_id SET DEFAULT nextval('public.user_quiz_attempts_attempt_id_seq'::regclass);


--
-- Name: user_survey_responses response_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_survey_responses ALTER COLUMN response_id SET DEFAULT nextval('public.user_survey_responses_response_id_seq'::regclass);


--
-- Name: users user_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users ALTER COLUMN user_id SET DEFAULT nextval('public.users_user_id_seq'::regclass);


--
-- Name: virtual_emails email_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.virtual_emails ALTER COLUMN email_id SET DEFAULT nextval('public.virtual_emails_email_id_seq'::regclass);


--
-- Data for Name: achievements; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.achievements (achievement_id, name, description, difficulty, reward_money) FROM stdin;
1	Hello World	??????????????????????????? 500 ??????	Medium	50.00
2	First Bill Paid	?????????????????????????????????	Medium	100.00
3	Syntax Hero	????????????????????????????? Error ??? 1 ?????	Medium	50.00
4	Coffee Lover	?????????????/????????????????????? 5 ?????	Medium	20.00
5	Junior Developer	????????????????????? 10 ???	Medium	150.00
6	Bug Squasher	???????????????????????? 20 ???	Medium	100.00
7	Survivor Week	????????????????????????? (7 ???) ????????????????	Medium	200.00
8	Night Owl	???????????? (????????????????????) ????????? 3 ???	Medium	50.00
9	Fast Typer	?????????????????????????? 30% ?????????????????	Medium	80.00
10	Savings Starter	??????????????????????????? 5,000 ???	Medium	100.00
11	Full Stack Master	???????????? (Skill) ?????????????????????	Hard	500.00
12	Deadline Fighter	?????????????????? 5 ????????????????? Deadline	Hard	300.00
13	Crisis Manager	??????????????????????????????????????????????? 10 ???	Hard	500.00
14	Senior Developer	????????????????????? 50 ???	Hard	1000.00
15	No StackOverflow	????????????? (Hard Task) ??????????????????????	Hard	800.00
16	High Roller	????????????????? 100,000 ???	Hard	2000.00
17	Arena Champion	?????????????????????????? 5 ??????????????	Hard	1500.00
18	Month Survivor	??????????????????????? (30 ???) ?????????	Hard	1000.00
19	Python God	??????????????????????????? 10,000,000 ???	Very Hard	10000.00
20	Immortal Coder	?????????????????????????????? (Fail) ???????????????????	Very Hard	5000.00
\.


--
-- Data for Name: active_accepted_challenges; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.active_accepted_challenges (user_id, challenge_id, code_state, started_at) FROM stdin;
24	1		2026-07-16 23:13:29.785249
\.


--
-- Data for Name: advanced_validation; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.advanced_validation (id, question_text, correct_answer) FROM stdin;
1	?????????? len([1, 2, 3]) ????????	3
2	???????????????? Dictionary ?????	{}
3	?????????? "Hello"[1] ????????	e
4	?????? for i in range(3) ??????????????	3
5	?????????? type(3.14) ????????	float
6	try-except ??????????	?????? Error
7	???????? def greet(): return "Hi" ????????????????	greet()
8	list.append(x) ???????	????? x ??????? list
9	?????????? 10 // 3 ????????	3
10	?????? import ??????????	???????????
\.


--
-- Data for Name: advanced_validation_choices; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.advanced_validation_choices (id, question_id, choice_text) FROM stdin;
1	1	3
2	1	2
3	1	4
4	1	Error
5	2	{}
6	2	[]
7	2	()
8	2	dict[]
9	3	e
10	3	H
11	3	l
12	3	Error
13	4	3
14	4	2
15	4	4
16	4	1
17	5	float
18	5	int
19	5	str
20	5	double
21	6	?????? Error
22	6	?????
23	6	???????????
24	6	??????????
25	7	greet()
26	7	call greet
27	7	run greet
28	7	def greet
29	8	????? x ??????? list
30	8	?? x ?????? list
31	8	??????????? list
32	8	????? list ????
33	9	3
34	9	3.33
35	9	1
36	9	10
37	10	???????????
38	10	?????????????
39	10	??????
40	10	??????
\.


--
-- Data for Name: assessment_choices; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.assessment_choices (id, question_id, choice_text, "order") FROM stdin;
\.


--
-- Data for Name: assessment_questions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.assessment_questions (id, level_value, question_text, question_type, correct_answer) FROM stdin;
\.


--
-- Data for Name: cosmetics; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cosmetics (cosmetic_id, name, type, price, asset_url) FROM stdin;
1	Ocean Theme	theme	500	theme-ocean
2	Sakura Theme	theme	750	theme-sakura
3	Cyberpunk Theme	theme	1000	theme-cyberpunk
4	Bronze Avatar Frame	avatar_frame	200	frame-bronze
5	Gold Avatar Frame	avatar_frame	500	frame-gold
\.


--
-- Data for Name: email_verifications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.email_verifications (id, user_id, token, expires_at, verified_at, created_at) FROM stdin;
1	15	c5b49f681d8150c60185208b4550f600f511032754224206abfc149b902bf4cc	2026-03-31 03:31:02.64193	\N	2026-03-30 03:31:02.64193
4	20	abdec072e20649618c3caa6780329e7b2f6a7685b059062b2f4df52dfa2535a3	2026-07-17 20:22:49.831001	\N	2026-07-16 20:22:49.831001
5	21	d36875f8741f3f61c76eda4fd87940ac3d728f195d7ed768238b427e625119f4	2026-07-17 20:25:22.511559	\N	2026-07-16 20:25:22.511559
7	23	1ff1e483f8e6bf0740b25c19f6a88703ee3e71dca8805ecc255ef1c0a5a595ab	2026-07-17 20:29:39.063894	\N	2026-07-16 20:29:39.063894
8	24	569439cf15ca91b493ebe464388d5b43d30b2f5ea94a96dbd021a2baccc6af9c	2026-07-17 20:38:18.326305	\N	2026-07-16 20:38:18.326305
\.


--
-- Data for Name: exercise_submissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.exercise_submissions (submission_id, user_id, exercise_id, submitted_code, is_passed, score, execution_time_ms, error_message, submitted_at) FROM stdin;
3	16	1	print("Hello, Python!")	t	100	\N	\N	2026-03-30 10:47:31.438179
4	16	8	# ??????????????????????\nprint("Comments ready")	t	100	\N	\N	2026-03-30 11:41:14.421025
5	16	7	print("Hello, Python!")	t	100	\N	\N	2026-03-30 12:06:36.998888
6	8	7	print("Hello, Python!")	t	100	\N	\N	2026-03-30 13:03:57.982758
\.


--
-- Data for Name: exercises; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.exercises (exercise_id, lesson_id, title, description, starter_code, solution_code, test_cases, xp_reward, currency_reward) FROM stdin;
1	1	?????????? Python	??????????????????????? "Hello, Python!" ???????????? 1 ??????	print("Hello, Python!")	print("Hello, Python!")	[{"input": "", "expected": "Hello, Python!"}]	15	5
2	2	???????????????????	??????????????? name ????????? "PySim" ?????????????????????????????	name = "PySim"\nprint(name)	name = "PySim"\nprint(name)	[{"input": "", "expected": "PySim"}]	20	6
3	3	?????????????????	???????????????? 1 ??? ??????????????????????? "?????? <????>"	name = input()\nprint("??????", name)	name = input()\nprint("??????", name)	[{"input": "?????", "expected": "?????? ?????"}, {"input": "Lumi", "expected": "?????? Lumi"}]	25	8
4	4	???????????????	???????? 1 ??? ??????????????? 50 ????????????? "????" ??????????? 50 ??????? "???????"	score = int(input())\nif score >= 50:\n    print("????")\nelse:\n    print("???????")	score = int(input())\nif score >= 50:\n    print("????")\nelse:\n    print("???????")	[{"input": "80", "expected": "????"}, {"input": "42", "expected": "???????"}]	30	10
5	5	?????? 1 ??? n	???????????? n ????????????????????? 1 ??? n ??????????	n = int(input())\nfor i in range(1, n + 1):\n    print(i)	n = int(input())\nfor i in range(1, n + 1):\n    print(i)	[{"input": "3", "expected": "1\\n2\\n3"}, {"input": "1", "expected": "1"}]	35	12
6	6	???????????????????	????????????? add(a, b) ??????????????????????????????? ????????????????????????????	def add(a, b):\n    return a + b\n\na = int(input())\nb = int(input())\nprint(add(a, b))	def add(a, b):\n    return a + b\n\na = int(input())\nb = int(input())\nprint(add(a, b))	[{"input": "2\\n3", "expected": "5"}, {"input": "10\\n7", "expected": "17"}]	40	15
7	1001	?????????: Hello World & print()	??????????????????????? "Hello, Python!" ???????????? 1 ??????	print("Hello, Python!")	print("Hello, Python!")	[{"input": "", "expected": "Hello, Python!"}]	15	5
8	1002	?????????: Comments ???????????????	????????????????? comment ?????? 1 ?????? ?????????????? "Comments ready"	# ??????????????????????\nprint("Comments ready")	# ??????????????????????\nprint("Comments ready")	[{"input": "", "expected": "Comments ready"}]	15	5
\.


--
-- Data for Name: learning_ai_tasks; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.learning_ai_tasks (task_id, user_id, mode, title, section_label, subtitle, accent, instructions_json, example_input, example_output, starter_code, test_cases_json, reward_xp, reward_coins, rerolls_used, max_rerolls, status, ai_payload, created_at, updated_at, completed_at) FROM stdin;
1	1	exercise	Fix the Tax Calculator	Exercise	Debug Lab	blue	["???????????????????????????????????? ???????????????????????? 7%","????????????????????????????? Tax is [value]"]	10000	Tax is 700.0	salary = int(input("Enter salary: "))\ntax = salary * 7\nprint(f"Tax is {tax}")	[{"input":"10000","expected":"Tax is 700.0"},{"input":"500","expected":"Tax is 35.0"},{"input":"150000","expected":"Tax is 10500.0"}]	90	20	0	3	ACTIVE	{"title":"Fix the Tax Calculator","sectionLabel":"Exercise","subtitle":"Debug Lab","accent":"blue","instructions":["???????????????????????????????????? ???????????????????????? 7%","????????????????????????????? Tax is [value]"],"example":{"input":"10000","output":"Tax is 700.0"},"starterCode":"salary = int(input(\\"Enter salary: \\"))\\ntax = salary * 7\\nprint(f\\"Tax is {tax}\\")","testCases":[{"input":"10000","expected":"Tax is 700.0"},{"input":"500","expected":"Tax is 35.0"},{"input":"150000","expected":"Tax is 10500.0"}],"rewardXp":90,"rewardCoins":20}	2026-03-30 03:05:52.798921	2026-03-30 03:05:52.798921	\N
2	8	challenge	FizzBuzz Counter	Hard Challenge	Challenge	rose	["Create a function called fizzbuzz that takes a number n as input","Return 'Fizz' if n is divisible by 3, 'Buzz' if divisible by 5, 'FizzBuzz' if divisible by both, otherwise return the number as a string"]	15	FizzBuzz	# Define your fizzbuzz function below\n\ndef fizzbuzz(n):\n    # Your code here\n    pass\n	[{"input":"3","expected":"Fizz"},{"input":"5","expected":"Buzz"},{"input":"15","expected":"FizzBuzz"},{"input":"7","expected":"7"}]	250	70	0	3	ACTIVE	{"title":"FizzBuzz Counter","sectionLabel":"Hard Challenge","subtitle":"Challenge","accent":"rose","instructions":["Create a function called fizzbuzz that takes a number n as input","Return 'Fizz' if n is divisible by 3, 'Buzz' if divisible by 5, 'FizzBuzz' if divisible by both, otherwise return the number as a string"],"example":{"input":"15","output":"FizzBuzz"},"starterCode":"# Define your fizzbuzz function below\\n\\ndef fizzbuzz(n):\\n    # Your code here\\n    pass\\n","testCases":[{"input":"3","expected":"Fizz"},{"input":"5","expected":"Buzz"},{"input":"15","expected":"FizzBuzz"},{"input":"7","expected":"7"}],"rewardXp":250,"rewardCoins":70}	2026-03-30 04:16:33.194297	2026-03-30 04:16:33.194297	\N
3	8	exercise	Fix the Greeting Bot	Exercise	Debug Lab	blue	["The code should ask for a user's name and print a personalized greeting message.","Find and fix the bug(s) so the greeting displays correctly with the user's name."]	Alice	Hello, Alice!	name = input("Enter your name: ")\nprint("Hello, " + name)\nprint("!")	[{"input":"Alice","expected":"Hello, Alice!"},{"input":"Bob","expected":"Hello, Bob!"},{"input":"Sam","expected":"Hello, Sam!"},{"input":"123","expected":"Hello, 123!"}]	120	30	1	3	ACTIVE	{"title":"Fix the Greeting Bot","sectionLabel":"Exercise","subtitle":"Debug Lab","accent":"blue","instructions":["The code should ask for a user's name and print a personalized greeting message.","Find and fix the bug(s) so the greeting displays correctly with the user's name."],"example":{"input":"Alice","output":"Hello, Alice!"},"starterCode":"name = input(\\"Enter your name: \\")\\nprint(\\"Hello, \\" + name)\\nprint(\\"!\\")","testCases":[{"input":"Alice","expected":"Hello, Alice!"},{"input":"Bob","expected":"Hello, Bob!"},{"input":"Sam","expected":"Hello, Sam!"},{"input":"123","expected":"Hello, 123!"}],"rewardXp":120,"rewardCoins":30}	2026-03-30 04:16:38.115372	2026-03-30 04:18:46.011888	\N
4	16	exercise	Fix the Grade Calculator	Exercise	Debug Lab	blue	["This code should calculate a letter grade (A, B, C, D, or F) based on a numeric score.","Find and fix the bugs: there's a syntax error, a logical error in the condition, and a missing return for one grade."]	85	B	def get_grade(score):\n    if score >= 90\n        return "A"\n    elif score >= 70:\n        return "B"\n    elif score >= 60:\n        return "C"\n    elif score >= 50:\n    elif score < 50:\n        return "F"\n\nresult = get_grade(int(input()))\nprint(result)	[{"input":"95","expected":"A"},{"input":"85","expected":"B"},{"input":"65","expected":"C"},{"input":"40","expected":"F"}]	120	30	0	3	ACTIVE	{"title":"Fix the Grade Calculator","sectionLabel":"Exercise","subtitle":"Debug Lab","accent":"blue","instructions":["This code should calculate a letter grade (A, B, C, D, or F) based on a numeric score.","Find and fix the bugs: there's a syntax error, a logical error in the condition, and a missing return for one grade."],"example":{"input":"85","output":"B"},"starterCode":"def get_grade(score):\\n    if score >= 90\\n        return \\"A\\"\\n    elif score >= 70:\\n        return \\"B\\"\\n    elif score >= 60:\\n        return \\"C\\"\\n    elif score >= 50:\\n    elif score < 50:\\n        return \\"F\\"\\n\\nresult = get_grade(int(input()))\\nprint(result)","testCases":[{"input":"95","expected":"A"},{"input":"85","expected":"B"},{"input":"65","expected":"C"},{"input":"40","expected":"F"}],"rewardXp":120,"rewardCoins":30}	2026-03-30 06:17:19.577027	2026-03-30 06:17:19.577027	\N
5	16	challenge	Even or Odd Checker	Hard Challenge	Challenge	rose	["Define a function named check_number that takes one parameter (a number)","Return 'even' if the number is even, 'odd' if the number is odd"]	4	even	# Define your function here\ndef check_number(n):\n    # Your code here\n    pass	[{"input":"2","expected":"even"},{"input":"7","expected":"odd"},{"input":"0","expected":"even"},{"input":"-3","expected":"odd"}]	250	70	1	3	ACTIVE	{"title":"Even or Odd Checker","sectionLabel":"Hard Challenge","subtitle":"Challenge","accent":"rose","instructions":["Define a function named check_number that takes one parameter (a number)","Return 'even' if the number is even, 'odd' if the number is odd"],"example":{"input":"4","output":"even"},"starterCode":"# Define your function here\\ndef check_number(n):\\n    # Your code here\\n    pass","testCases":[{"input":"2","expected":"even"},{"input":"7","expected":"odd"},{"input":"0","expected":"even"},{"input":"-3","expected":"odd"}],"rewardXp":250,"rewardCoins":70}	2026-03-30 06:17:25.062755	2026-03-30 11:42:52.494573	\N
6	18	challenge	Temperature Converter	Hard Challenge	Challenge	rose	["Create a function named celsius_to_fahrenheit that takes a single argument representing a temperature in Celsius.",""]	25	77.0	# Define your function below:\n# def celsius_to_fahrenheit(celsius):\n#     # Calculate the Fahrenheit equivalent\n#     # Return the result\n\n# Conversion logic: (Celsius * 9/5) + 32	[{"input":"0","expected":"32.0"},{"input":"25","expected":"77.0"},{"input":"100","expected":"212.0"}]	220	60	0	3	ACTIVE	{"title":"Temperature Converter","sectionLabel":"Hard Challenge","subtitle":"Challenge","accent":"rose","instructions":["Create a function named celsius_to_fahrenheit that takes a single argument representing a temperature in Celsius.",""],"example":{"input":"25","output":"77.0"},"starterCode":"# Define your function below:\\n# def celsius_to_fahrenheit(celsius):\\n#     # Calculate the Fahrenheit equivalent\\n#     # Return the result\\n\\n# Conversion logic: (Celsius * 9/5) + 32","testCases":[{"input":"0","expected":"32.0"},{"input":"25","expected":"77.0"},{"input":"100","expected":"212.0"}],"rewardXp":220,"rewardCoins":60}	2026-07-16 20:18:22.467979	2026-07-16 20:18:22.467979	\N
7	24	challenge	Count the Vowels	Hard Challenge	Challenge	rose	["Create a variable named "word" and assign the string 'Programming' to it.","Count how many vowels (a, e, i, o, u) are in the word. Treat both uppercase and lowercase letters as vowels.","Print the result in the exact format: 'Number of vowels: X' where X is the counted number."]		Number of vowels: 3	# Write your code here to count and print the vowels\n	[{"input":"","expected":"Number of vowels: 3"},{"input":"","expected":"Number of vowels: 3"},{"input":"","expected":"Number of vowels: 3"}]	250	70	0	3	ACTIVE	{"title":"Count the Vowels","sectionLabel":"Hard Challenge","subtitle":"Challenge","accent":"rose","instructions":["Create a variable named "word" and assign the string 'Programming' to it.","Count how many vowels (a, e, i, o, u) are in the word. Treat both uppercase and lowercase letters as vowels.","Print the result in the exact format: 'Number of vowels: X' where X is the counted number."],"example":{"input":"","output":"Number of vowels: 3"},"starterCode":"# Write your code here to count and print the vowels\\n","testCases":[{"input":"","expected":"Number of vowels: 3"},{"input":"","expected":"Number of vowels: 3"},{"input":"","expected":"Number of vowels: 3"}],"rewardXp":250,"rewardCoins":70}	2026-07-16 20:39:11.976003	2026-07-16 20:39:11.976003	\N
\.


--
-- Data for Name: lesson_quizzes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.lesson_quizzes (quiz_id, lesson_id, quiz_type) FROM stdin;
1	1	pre
2	2	pre
3	4	pre
4	5	pre
1001	1001	pre
1002	1001	post
1003	1002	pre
1004	1002	post
1005	1003	pre
1006	1003	post
\.


--
-- Data for Name: lesson_slides; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.lesson_slides (slide_id, lesson_id, slide_order, slide_title, slide_content, slide_src, slide_type) FROM stdin;
17	1	1	Python ????????	Python ????????????????????????????????????????????? ????????? ??????????????????????\n?????????????????: Web, Data Science, AI, Automation	\N	text
18	1	2	???????? Python?	????????????????????????\n????????? ?? library ????\n??????????????????\n?????????????????????????????	\N	text
19	1	3	Hello, World!	print("Hello, World!")	\N	code
20	2	1	??????????????	?????? (Variable) ??? ???????????????????? ?? Python ???????????????????????\n\nname = "?????"\nage = 20\nheight = 170.5\nis_student = True	\N	text
21	2	2	?????????????????	int   = ?????????  ???? 42\nfloat = ??????    ???? 3.14\nstr   = ???????   ???? "Hello"\nbool  = ????????  True ???? False	\N	text
22	2	3	????????????	name = "Python"\nversion = 3\npi = 3.14\nprint(type(name))\nprint(type(version))\nprint(type(pi))	\N	code
23	3	1	????????????? print()	print() ?????????????????????????\n\nprint("??????")\nprint(42)\nprint("????:", "?????")	\N	text
24	3	2	???????????????? input()	input() ?????????????????? ??????????????? str ????\n\nname = input("????: ")\nprint("??????", name)\nage = int(input("????: "))\nprint("???????", age, "??")	\N	text
25	3	3	????????????	name = input("?????????????: ")\nprint("????????????", name, "?????? Python!")	\N	code
26	4	1	???????? if / elif / else	??????????????????????????\n\nif ????????:\n    ??????\nelif ????????????:\n    ??????\nelse:\n    ??????	\N	text
27	4	2	???????? if/else	score = 75\n\nif score >= 80:\n    print("???? A")\nelif score >= 70:\n    print("???? B")\nelif score >= 60:\n    print("???? C")\nelse:\n    print("???????")	\N	code
28	5	1	???????? for	for ????????????????????????\n\nfor i in range(5):\n    print(i)   # 0 1 2 3 4\n\nfor x in ["???","?????","???????"]:\n    print(x)	\N	text
29	5	2	???????? while	while ?????????????????????????? True\n\nn = 1\nwhile n <= 5:\n    print(n)\n    n += 1	\N	text
30	5	3	?????? for loop	total = 0\nfor i in range(1, 11):\n    total += i\nprint("????? 1-10 =", total)	\N	code
31	6	1	???????? (Function) ????????	????????????????????????????? ????????????????????\n\ndef ????????????(???????????):\n    ??????\n    return ?????????????	\N	text
32	6	2	????????????????	def greet(name):\n    return "?????? " + name + "!"\n\ndef add(a, b):\n    return a + b\n\nprint(greet("Python"))\nprint(add(10, 20))	\N	code
1001	1001	1	Python ????????	Python ???????????????????????????? ??????????????????????\n???????? Guido van Rossum ???? 1991	/gif/first_print.gif	text
1002	1001	2	?????? print()	????????? print() ????????????????\n????????: print("Hello World!")	\N	text
1003	1001	3	????????????	print("Hello World!")\nprint("????????? Python!")	\N	code
1004	1002	1	Comments ????????	Comments ??????????????????????? Python ?????????????????\n?????????????? # ??????	/gif/comments.gif	text
1005	1002	2	???????? Comment	# ?????? Comment\nprint("Hello") # Comment ??????????\n\n# ??????????\n# ??? # ???????	\N	code
1006	1003	1	??????????????????	????????? input() ????????????????? keyboard\n?????????????????? string ????	/gif/input.gif	text
1007	1003	2	???????? Input	name = input("????????: ")\nprint("??????", name)	\N	code
1008	1004	1	??????????????	?????? (Variable) ??? "?????" ??????????\n?? Python ?????????????????????????	/gif/python4.gif	text
1009	1004	2	?????????????????	x = 10\nname = "John"\nmy_list = [1, 2, 3]\n\n# ?????????????:\n# - ????????????????????? _\n# - ???????????????????\n# - case-sensitive	\N	code
1010	1006	1	Type Conversion	????????????????? ???? str ???? int\n??? int(), float(), str()	/gif/typeconversion.gif	text
1011	1006	2	???????? Type Conversion	x = "100"\ny = int(x)  # ???? str ???? int\nprint(y + 50)  # ??????? 150\n\nz = float("3.14")\nprint(z)  # 3.14	\N	code
\.


--
-- Data for Name: lessons; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.lessons (lesson_id, module_id, title, content, order_index, required_level, description) FROM stdin;
1	1	????? Python	\N	1	0	???????????? Python ?????????????
2	1	???????????????????	\N	2	0	int, float, str, bool
3	1	?????????????????????	\N	3	0	input() ??? print()
4	2	???????? if / else	\N	1	1	????????????????????
5	2	???????? for / while	\N	2	1	?????????????????
6	3	????????????????	\N	1	5	def ???????????? return
1001	1001	Hello World & print()	\N	1	0	\N
1002	1001	Comments ???????????????	\N	2	0	\N
1003	1001	Input ?????????	\N	3	0	\N
1004	1002	?????? (Variables)	\N	1	0	\N
1005	1002	?????????? (Data Types)	\N	2	0	\N
1006	1002	Type Conversion	\N	3	0	\N
1007	1003	If-Else	\N	1	2	\N
1008	1003	For Loop	\N	2	2	\N
1009	1003	While Loop	\N	3	3	\N
1010	1004	????????????????	\N	1	4	\N
1011	1004	Parameters & Return	\N	2	5	\N
1012	1005	List	\N	1	6	\N
1013	1005	Dictionary	\N	2	7	\N
1014	1006	????/?????????	\N	1	8	\N
1015	1006	Try-Except	\N	2	9	\N
\.


--
-- Data for Name: level_config; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.level_config (id, q_id, title, level_value, "order") FROM stdin;
1001	1003	Beginner	1	1
1002	1003	Advanced	10	2
\.


--
-- Data for Name: modules; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.modules (module_id, title, description, order_index, is_locked, required_level) FROM stdin;
1	Python ???????	??????????????? Python ???????????????	1	t	0
2	????????????????	if/else ??????????? for/while	2	t	1
3	????????????????	???????????????? ???????????? module	3	t	5
1001	??????? Python	\N	1	t	0
1002	???????????????????	\N	2	t	0
1003	??????????????	\N	3	t	2
1004	????????	\N	4	t	4
1005	???????????????	\N	5	t	6
1006	??????? Exception	\N	6	t	8
\.


--
-- Data for Name: multiplayer_challenges; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.multiplayer_challenges (challenge_id, title, description, difficulty, reward, time_limit, test_cases, created_by, created_at, is_test, expires_at) FROM stdin;
1	Password Generator	Write a Python script that prints a random 4-digit PIN code (1000-9999). Use the random module. Print only the PIN.	Easy	800	300	[{"input": "", "output": "regexp:\\\\d{4}"}]	\N	2026-07-16 19:35:45.935368	0	2026-07-23 23:04:37.683153
2	VAT Calculator	Write a Python script that takes a price (float) as input, calculates 7% VAT, and prints the VAT amount rounded to 2 decimal places.	Easy	1000	300	[{"input": "100\\n", "output": "7.00\\n"}, {"input": "250\\n", "output": "17.50\\n"}]	\N	2026-07-16 19:35:45.951745	0	2026-07-23 23:04:37.683153
3	Even or Odd check	Write a Python script that takes an integer as input. If it is even, print 'Even'. If it is odd, print 'Odd'.	Easy	500	300	[{"input": "4\\n", "output": "Even\\n"}, {"input": "7\\n", "output": "Odd\\n"}]	\N	2026-07-16 19:35:45.967638	0	2026-07-23 23:04:37.683153
4	Test Challenge 1: Hello World	Write a Python script that prints 'Hello World'. Even an empty file submission will pass and earn rewards for testing purposes.	Easy	350	9999999	[{"input": "", "output": "Hello World\\n"}]	\N	2026-07-16 23:04:37.758852	1	2099-12-31 23:59:59
5	Test Challenge 2: Number Adder	Write a Python script that takes two inputs and prints their sum. Even an empty file submission will pass and earn rewards for testing purposes.	Easy	500	9999999	[{"input": "4\\n5\\n", "output": "9\\n"}]	\N	2026-07-16 23:04:37.787736	1	2099-12-31 23:59:59
6	ทดสอบระบบ1	1234	Easy	950	500	[{"input": "", "output": ""}]	24	2026-07-16 23:25:31.94075	0	2026-07-17 23:25:31.913
\.


--
-- Data for Name: multiplayer_sessions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.multiplayer_sessions (session_id, mode, status, current_round, created_at) FROM stdin;
\.


--
-- Data for Name: multiplayer_submissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.multiplayer_submissions (submission_id, session_id, user_id, challenge_id, code, score, passed_cases, total_cases, ai_feedback, submitted_at, efficiency_ms) FROM stdin;
3	\N	24	1		100	1	1	{"review": "ผ่านการประเมินเพื่อจำลองระบบทดสอบ"}	2026-07-16 23:32:49.292549	12
\.


--
-- Data for Name: music_tracks; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.music_tracks (track_id, track_name, file_path, is_default) FROM stdin;
\.


--
-- Data for Name: question_choices; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.question_choices (choice_id, question_id, choice_text) FROM stdin;
1	1	????????????
2	1	???????????
3	1	?????????????
4	1	?????????????
5	2	print()
6	2	echo()
7	2	show()
8	2	display()
9	3	str
10	3	int
11	3	float
12	3	bool
13	4	float
14	4	int
15	4	str
16	4	bool
17	5	if
18	5	for
19	5	while
20	5	def
21	6	0 ??? 4
22	6	1 ??? 5
23	6	0 ??? 5
24	6	1 ??? 4
1001	1001	print()
1002	1001	echo()
1003	1001	write()
1004	1001	console.log()
1005	1004	print("??????")
1006	1004	echo("??????")
1007	1004	say "??????"
1008	1004	output("??????")
1009	1005	Compiled
1010	1005	Interpreted
1011	1005	Assembly
1012	1005	Machine Language
1013	1006	#
1014	1006	//
1015	1006	/*
1016	1006	--
1017	1007	???????
1018	1007	????????????????????
1019	1007	????????? Error
1020	1007	??????????????
1021	1008	Comment
1022	1008	??????
1023	1008	????????
1024	1008	Operator
1025	1009	# This is a comment
1026	1009	// This is a comment
1027	1009	/* This is a comment */
1028	1009	-- This is a comment
1029	1010	input()
1030	1010	read()
1031	1010	scanf()
1032	1010	get()
1033	1011	str
1034	1011	int
1035	1011	float
1036	1011	bool
1037	1012	str
1038	1012	int
1039	1012	float
1040	1012	list
1041	1013	??? int(input())
1042	1013	??? input(int)
1043	1013	??? number(input())
1044	1013	?????????????
\.


--
-- Data for Name: quiz_questions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.quiz_questions (question_id, quiz_id, question_order, question_text, question_type, correct_answer) FROM stdin;
1	1	1	Python ????????????????????????	choice	????????????
2	1	2	??????????????????? Python?	choice	print()
3	2	1	????????????????????????	choice	str
4	2	2	x = 10.5 ?????????????????????	choice	float
5	3	1	???????????????????????????? Python?	choice	if
6	4	1	range(5) ?????????????????????????????????	choice	0 ??? 4
1001	1001	1	?????????????????????????? Python?	choice	print()
1002	1001	2	?????????? print("Hello") ????????	fill	Hello
1003	1002	1	print("Python") ?????????????	fill	Python
1004	1002	2	????????????????	choice	print("??????")
1005	1002	3	Python ??????????????	choice	Interpreted
1006	1003	1	Comment ?? Python ???????????????????	choice	#
1007	1003	2	Comment ?????????????????????????????????	choice	???????
1008	1004	1	??????????? # ?? Python ??????????????????	choice	Comment
1009	1004	2	???????????? Comment ???????????	choice	# This is a comment
1010	1005	1	??????????????????????????????	choice	input()
1011	1005	2	?????????? input() ?????????????????????	choice	str
1012	1006	1	name = input("????: ") ?????? name ???????????	choice	str
1013	1006	2	?????????????????????? input ??????????????	choice	??? int(input())
\.


--
-- Data for Name: session_players; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.session_players (session_id, user_id, money_balance, is_survived, score, status) FROM stdin;
\.


--
-- Data for Name: shop_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.shop_items (item_id, name, description, item_type, price, asset_url, preview_image, is_active, effects) FROM stdin;
41	fsdf		profile_background	0	http://localhost:5000/uploads/1772867494875-72153669.jpg		t	[]
42	ffff		theme	0	\N	\N	t	[{"size": 24, "color": "#FF69B4", "visual": "??", "trigger": "click", "duration": 800}]
34	asd		theme	0	\N	\N	t	[{"size": 24, "color": "#FF69B4", "visual": "??", "trigger": "click", "duration": 800}]
35	rtt		theme	0	\N	\N	t	[{"size": 24, "color": "#12f32c", "visual": "https://i.pinimg.com/originals/48/49/75/48497592504e248948b39e71c644e26e.jpg", "trigger": "click", "duration": 800}]
37	?nasd		profile_background	0	http://localhost:5000/uploads/1772732995094-745411319.jpg		t	[]
38	?nam		profile_frame	0	http://localhost:5000/uploads/1772734723648-640372036.png		t	[]
\.


--
-- Data for Name: survey_options; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.survey_options (id, question_id, option_text, option_description, "order") FROM stdin;
1	1	????????? Programming	???????????? Python ?????????????????????? IT	1
2	1	??????????????? / AI	???? Data Science, Machine Learning ???? AI	2
3	1	??????????????????	????????????, ???? ??????????????????????	3
4	1	???????????????????????	????????????????????????????????	4
5	2	???????????	??????????? Python ?????? ??????????????????????	1
6	2	?????????????????	???????? Python ?????? ???????????????????????	2
1001	1001	????????	?????????????????????????????	1
1002	1001	???????	???????????????????????????????	2
1003	1001	??????????	????????????????????????????	3
1004	1002	?????????????	????????????????????	1
1005	1002	???????????????	Data Science & Analytics	2
1006	1002	????????	Game Development	3
1007	1002	??????	????????????????????????????????	4
\.


--
-- Data for Name: survey_questions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.survey_questions (id, title, image, description) FROM stdin;
1	???????????????????????? Python ????????	survey1.png	????????????????????????????? ????????????????????????????????????????????
2	???????????? Python ??????????????????????????	survey2.png	?????????????????????????????? ?????????????????????????????????????????????
1001	?????????????????????????????????	cat-coding.png	?????????????????????????????????????????
1002	???????????? Python ?????????	cat-mascot.png	??????????????????????????????????????????????
1003	????????????????	cat-logo.png	???????????????????????????????
\.


--
-- Data for Name: user_achievements; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_achievements (id, user_id, achievement_id, unlocked_at) FROM stdin;
\.


--
-- Data for Name: user_cosmetics; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_cosmetics (user_id, cosmetic_id, is_equipped, purchased_at) FROM stdin;
\.


--
-- Data for Name: user_mailbox; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_mailbox (mail_id, user_id, title, content, attachment_coins, is_read, is_claimed, created_at) FROM stdin;
3	24	ผลการประลองโจทย์: Test Challenge 1: Hello World	ขอแสดงความยินดี! คุณได้อันดับที่ 1 จากการเข้าร่วมแข่งขันในโจทย์ 'Test Challenge 1: Hello World' ผลคะแนนของคุณคือ 100/100 และได้รับรางวัลเป็นจำนวน 350 Code Coins (โหมดจำลองระบบทดสอบ)	350	1	1	2026-07-16 23:21:24.409462
4	24	ผลการประลองโจทย์: Test Challenge 2: Number Adder	ขอแสดงความยินดี! คุณได้อันดับที่ 1 จากการเข้าร่วมแข่งขันในโจทย์ 'Test Challenge 2: Number Adder' ผลคะแนนของคุณคือ 100/100 และได้รับรางวัลเป็นจำนวน 500 Code Coins (โหมดจำลองระบบทดสอบ)	500	1	1	2026-07-16 23:21:36.509435
5	24	ผลการประลองโจทย์: Test Challenge 1: Hello World	ขอแสดงความยินดี! คุณได้อันดับที่ 1 จากการเข้าร่วมแข่งขันในโจทย์ 'Test Challenge 1: Hello World' ผลคะแนนของคุณคือ 100/100 และได้รับรางวัลเป็นจำนวน 350 Code Coins (โหมดจำลองระบบทดสอบ)	350	1	1	2026-07-16 23:26:15.11861
7	24	ผลการประลองโจทย์: Test Challenge 2: Number Adder	ขอแสดงความยินดี! คุณได้อันดับที่ 1 จากการเข้าร่วมแข่งขันในโจทย์ 'Test Challenge 2: Number Adder' ผลคะแนนของคุณคือ 100/100 และได้รับรางวัลเป็นจำนวน 500 Code Coins (โหมดจำลองระบบทดสอบ)	500	1	1	2026-07-16 23:26:25.924791
6	24	ผลการประลองโจทย์: Test Challenge 1: Hello World	ขอแสดงความยินดี! คุณได้อันดับที่ 1 จากการเข้าร่วมแข่งขันในโจทย์ 'Test Challenge 1: Hello World' ผลคะแนนของคุณคือ 100/100 และได้รับรางวัลเป็นจำนวน 350 Code Coins (โหมดจำลองระบบทดสอบ)	350	1	1	2026-07-16 23:26:23.295463
\.


--
-- Data for Name: user_missions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_missions (user_mission_id, user_id, email_id, status, accepted_at, completed_at) FROM stdin;
\.


--
-- Data for Name: user_progress; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_progress (progress_id, user_id, lesson_id, status, score, completed_at) FROM stdin;
\.


--
-- Data for Name: user_quiz_attempts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_quiz_attempts (attempt_id, user_id, lesson_id, quiz_type, score, total_questions, passed, created_at) FROM stdin;
1	8	1	pre	2	2	t	2026-03-30 02:00:04.752545
2	8	4	pre	0	1	f	2026-03-30 02:00:35.073961
3	8	5	pre	1	1	t	2026-03-30 02:00:55.571731
4	8	2	pre	2	2	t	2026-03-30 06:04:51.781592
5	16	1	pre	1	2	t	2026-03-30 06:12:42.925244
6	16	4	pre	0	1	f	2026-03-30 06:20:56.299236
\.


--
-- Data for Name: user_survey_responses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_survey_responses (response_id, user_id, question_id, selected_option, created_at) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (user_id, username, email, password_hash, role, level, xp, virtual_currency, created_at, reset_token, reset_token_expiry, is_deleted, deleted_at, is_banned, ban_until, reputation, equipped_theme_id, equipped_mouse_effect_id, equipped_profile_frame_id, avatar_url, bio) FROM stdin;
7	admin	teezarivkku@gmail.com	$2b$10$GlRJjqvHGWdN/HmHpFkRVuAjZbKwPCdj3IFZ1iXMftxL6bmUnU7xy	admin	1	0	0	2026-03-27 22:15:39.761276	\N	\N	f	\N	f	\N	10	\N	\N	\N	\N	\N
9	Fs	opporan@gmail.com	$2b$10$B3/lV13VJBElRhyJo2dB.e80A8GVWcaUeXI/JQ3s3Hw9oBPCal7nO	student	1	0	0	2026-03-28 05:53:42.196161	\N	\N	f	\N	f	\N	10	\N	\N	\N	\N	\N
10	Za	Tee@gmail.com	$2b$10$V2xbo6m7Onn.hIuFg0uhPOVEux70hRNTKyJIdHHUE32F5B2XSaJ4y	student	1	0	0	2026-03-28 06:02:11.003462	\N	\N	f	\N	f	\N	10	\N	\N	\N	\N	\N
11	pap	Ress@gmail.com	$2b$10$LVJtyizZEeAse3rDYlBNS.DSekViX65h2uUaeZXB65gOxzFErshA6	student	0	0	0	2026-03-28 06:08:17.073939	\N	\N	f	\N	f	\N	10	\N	\N	\N	\N	\N
12	pool	ypu@gmail.com	$2b$10$tefSsykgwJK6wsc4E6G61OwpgD0AWn3uA7SEJE0tQL5gTazJUBa0O	student	1	0	0	2026-03-28 06:31:13.31054	\N	\N	f	\N	f	\N	10	\N	\N	\N	\N	\N
13	pp	yu@gmail.com	$2b$10$YN2MFJQyVcuwf2yMExzgu.mZ6EcoS4NkS5rWkF3o5DEPEp/5mrTke	student	1	0	0	2026-03-28 15:36:49.95529	\N	\N	f	\N	f	\N	10	\N	\N	\N	\N	\N
14	tttt	oppp@gmail.com	$2b$10$8gxZH1BFFnpIiNPjJtB5WOWW5EB2ybuohWo.2usxxv8s.LvOIANbu	student	1	0	0	2026-03-28 15:38:31.528865	\N	\N	f	\N	f	\N	10	\N	\N	\N	\N	\N
15	teefgff	chak@gmail.com	$2b$10$oMt.2cJtRhXsRLHZGpeEHupL.NC83Al6BAkTHTM4xcEL/iSefp1Ye	user	0	0	0	2026-03-30 03:31:02.639771	\N	\N	f	\N	f	\N	10	\N	\N	\N	\N	\N
16	yyy	uoo@gmail.com	$2b$10$h6CCze/B8LgnfkRq7sgHKekrAvCXxm7w/6t/S92.0anfQguhrtYSq	student	1	45	15	2026-03-30 06:11:12.401276	\N	\N	f	\N	f	\N	10	\N	\N	\N	\N	\N
17	test1	pungpatpp100@gmail.com	$2b$10$4ojpulhIMjVRZmbWhy5Ra.SwjNOmpK1dD2.cGvreCQ77Dc44CaaBq	user	0	0	0	2026-07-16 20:20:05.435668	\N	\N	f	\N	f	\N	10	\N	\N	\N	\N	\N
18	test3	acd@gmail.com	$2b$10$b6XTrJl6H3psMDtbNy.FCuOO6WyBWXYMFRkCqosyy6BjgrmDHTMM2	user	0	0	0	2026-07-16 20:20:34.88909	\N	\N	f	\N	f	\N	10	\N	\N	\N	\N	\N
20	test2	age@gmail.com	$2b$10$ksMNy1gIZ2dNWVQPV/udk.PHfEdqcJyQKbcPXbrzwD2VWAIc.sZKe	user	0	0	0	2026-07-16 20:22:49.789946	\N	\N	f	\N	f	\N	10	\N	\N	\N	\N	\N
21	wener	wener0021@gmail.com	$2b$10$zFkbYe.FLFppUKMNnFWk..lIh3BKvjLHpYQ8kPBfgmD/WTDLvdseG	user	0	0	0	2026-07-16 20:25:22.473688	\N	\N	f	\N	f	\N	10	\N	\N	\N	\N	\N
23	wener02	test@mail.com	$2b$10$JN7B3ndnwThivxVb4a2F/.NPK5OE.nxUVBhQV2dXPCxCD4gBKRmQG	user	0	0	0	2026-07-16 20:29:39.028768	\N	\N	f	\N	f	\N	10	\N	\N	\N	\N	\N
8	tee	teerapat.boo@kkumail.com	$2b$10$iEaEJojH67CkONhI/wNn5.eaHx4EBA5DJCgv02Qq6XSRS7b9SZyWK	student	1	15	705	2026-03-27 22:17:52.182979	\N	\N	f	\N	f	\N	10	\N	\N	\N	\N	\N
24	pong	pungpatpp102092@gmail.com	$2b$10$2FVoO2W4axEN9anL9wxk.OnyGken32SQbpakOUNxCJXBpb8FWi5SW	user	0	0	2050	2026-07-16 20:38:18.289558	\N	\N	f	\N	f	\N	10	\N	\N	\N	\N	\N
\.


--
-- Data for Name: virtual_emails; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.virtual_emails (email_id, sender_name, subject, body_content, related_exercise_id, difficulty_level, sent_at) FROM stdin;
\.


--
-- Name: achievements_achievement_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.achievements_achievement_id_seq', 20, true);


--
-- Name: advanced_validation_choices_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.advanced_validation_choices_id_seq', 40, true);


--
-- Name: advanced_validation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.advanced_validation_id_seq', 10, true);


--
-- Name: assessment_choices_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.assessment_choices_id_seq', 1, false);


--
-- Name: assessment_questions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.assessment_questions_id_seq', 1, false);


--
-- Name: cosmetics_cosmetic_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cosmetics_cosmetic_id_seq', 5, true);


--
-- Name: email_verifications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.email_verifications_id_seq', 8, true);


--
-- Name: exercise_submissions_submission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.exercise_submissions_submission_id_seq', 6, true);


--
-- Name: exercises_exercise_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.exercises_exercise_id_seq', 8, true);


--
-- Name: learning_ai_tasks_task_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.learning_ai_tasks_task_id_seq', 7, true);


--
-- Name: lesson_quizzes_quiz_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.lesson_quizzes_quiz_id_seq', 1006, true);


--
-- Name: lesson_slides_slide_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.lesson_slides_slide_id_seq', 1011, true);


--
-- Name: lessons_lesson_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.lessons_lesson_id_seq', 1015, true);


--
-- Name: level_config_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.level_config_id_seq', 1002, true);


--
-- Name: modules_module_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.modules_module_id_seq', 1006, true);


--
-- Name: multiplayer_challenges_challenge_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.multiplayer_challenges_challenge_id_seq', 6, true);


--
-- Name: multiplayer_submissions_submission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.multiplayer_submissions_submission_id_seq', 3, true);


--
-- Name: music_tracks_track_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.music_tracks_track_id_seq', 1, true);


--
-- Name: question_choices_choice_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.question_choices_choice_id_seq', 1044, true);


--
-- Name: quiz_questions_question_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.quiz_questions_question_id_seq', 1013, true);


--
-- Name: shop_items_item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.shop_items_item_id_seq', 42, true);


--
-- Name: survey_options_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.survey_options_id_seq', 1007, true);


--
-- Name: survey_questions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.survey_questions_id_seq', 1003, true);


--
-- Name: user_achievements_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_achievements_id_seq', 1, false);


--
-- Name: user_mailbox_mail_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_mailbox_mail_id_seq', 7, true);


--
-- Name: user_missions_user_mission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_missions_user_mission_id_seq', 1, false);


--
-- Name: user_progress_progress_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_progress_progress_id_seq', 1, false);


--
-- Name: user_quiz_attempts_attempt_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_quiz_attempts_attempt_id_seq', 6, true);


--
-- Name: user_survey_responses_response_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_survey_responses_response_id_seq', 1, false);


--
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_user_id_seq', 24, true);


--
-- Name: virtual_emails_email_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.virtual_emails_email_id_seq', 1, false);


--
-- Name: achievements achievements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.achievements
    ADD CONSTRAINT achievements_pkey PRIMARY KEY (achievement_id);


--
-- Name: active_accepted_challenges active_accepted_challenges_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.active_accepted_challenges
    ADD CONSTRAINT active_accepted_challenges_pkey PRIMARY KEY (user_id, challenge_id);


--
-- Name: advanced_validation_choices advanced_validation_choices_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advanced_validation_choices
    ADD CONSTRAINT advanced_validation_choices_pkey PRIMARY KEY (id);


--
-- Name: advanced_validation advanced_validation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.advanced_validation
    ADD CONSTRAINT advanced_validation_pkey PRIMARY KEY (id);


--
-- Name: assessment_choices assessment_choices_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assessment_choices
    ADD CONSTRAINT assessment_choices_pkey PRIMARY KEY (id);


--
-- Name: assessment_questions assessment_questions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assessment_questions
    ADD CONSTRAINT assessment_questions_pkey PRIMARY KEY (id);


--
-- Name: cosmetics cosmetics_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cosmetics
    ADD CONSTRAINT cosmetics_pkey PRIMARY KEY (cosmetic_id);


--
-- Name: email_verifications email_verifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.email_verifications
    ADD CONSTRAINT email_verifications_pkey PRIMARY KEY (id);


--
-- Name: exercise_submissions exercise_submissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercise_submissions
    ADD CONSTRAINT exercise_submissions_pkey PRIMARY KEY (submission_id);


--
-- Name: exercises exercises_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercises
    ADD CONSTRAINT exercises_pkey PRIMARY KEY (exercise_id);


--
-- Name: learning_ai_tasks learning_ai_tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.learning_ai_tasks
    ADD CONSTRAINT learning_ai_tasks_pkey PRIMARY KEY (task_id);


--
-- Name: lesson_quizzes lesson_quizzes_lesson_id_quiz_type_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lesson_quizzes
    ADD CONSTRAINT lesson_quizzes_lesson_id_quiz_type_key UNIQUE (lesson_id, quiz_type);


--
-- Name: lesson_quizzes lesson_quizzes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lesson_quizzes
    ADD CONSTRAINT lesson_quizzes_pkey PRIMARY KEY (quiz_id);


--
-- Name: lesson_slides lesson_slides_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lesson_slides
    ADD CONSTRAINT lesson_slides_pkey PRIMARY KEY (slide_id);


--
-- Name: lessons lessons_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lessons
    ADD CONSTRAINT lessons_pkey PRIMARY KEY (lesson_id);


--
-- Name: level_config level_config_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.level_config
    ADD CONSTRAINT level_config_pkey PRIMARY KEY (id);


--
-- Name: modules modules_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.modules
    ADD CONSTRAINT modules_pkey PRIMARY KEY (module_id);


--
-- Name: multiplayer_challenges multiplayer_challenges_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.multiplayer_challenges
    ADD CONSTRAINT multiplayer_challenges_pkey PRIMARY KEY (challenge_id);


--
-- Name: multiplayer_sessions multiplayer_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.multiplayer_sessions
    ADD CONSTRAINT multiplayer_sessions_pkey PRIMARY KEY (session_id);


--
-- Name: multiplayer_submissions multiplayer_submissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.multiplayer_submissions
    ADD CONSTRAINT multiplayer_submissions_pkey PRIMARY KEY (submission_id);


--
-- Name: music_tracks music_tracks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.music_tracks
    ADD CONSTRAINT music_tracks_pkey PRIMARY KEY (track_id);


--
-- Name: question_choices question_choices_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.question_choices
    ADD CONSTRAINT question_choices_pkey PRIMARY KEY (choice_id);


--
-- Name: quiz_questions quiz_questions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_questions
    ADD CONSTRAINT quiz_questions_pkey PRIMARY KEY (question_id);


--
-- Name: session_players session_players_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session_players
    ADD CONSTRAINT session_players_pkey PRIMARY KEY (session_id, user_id);


--
-- Name: shop_items shop_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shop_items
    ADD CONSTRAINT shop_items_pkey PRIMARY KEY (item_id);


--
-- Name: survey_options survey_options_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.survey_options
    ADD CONSTRAINT survey_options_pkey PRIMARY KEY (id);


--
-- Name: survey_questions survey_questions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.survey_questions
    ADD CONSTRAINT survey_questions_pkey PRIMARY KEY (id);


--
-- Name: user_survey_responses unique_user_question; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_survey_responses
    ADD CONSTRAINT unique_user_question UNIQUE (user_id, question_id);


--
-- Name: user_achievements user_achievements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_achievements
    ADD CONSTRAINT user_achievements_pkey PRIMARY KEY (id);


--
-- Name: user_cosmetics user_cosmetics_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_cosmetics
    ADD CONSTRAINT user_cosmetics_pkey PRIMARY KEY (user_id, cosmetic_id);


--
-- Name: user_mailbox user_mailbox_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_mailbox
    ADD CONSTRAINT user_mailbox_pkey PRIMARY KEY (mail_id);


--
-- Name: user_missions user_missions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_missions
    ADD CONSTRAINT user_missions_pkey PRIMARY KEY (user_mission_id);


--
-- Name: user_progress user_progress_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_progress
    ADD CONSTRAINT user_progress_pkey PRIMARY KEY (progress_id);


--
-- Name: user_quiz_attempts user_quiz_attempts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_quiz_attempts
    ADD CONSTRAINT user_quiz_attempts_pkey PRIMARY KEY (attempt_id);


--
-- Name: user_quiz_attempts user_quiz_attempts_user_id_lesson_id_quiz_type_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_quiz_attempts
    ADD CONSTRAINT user_quiz_attempts_user_id_lesson_id_quiz_type_key UNIQUE (user_id, lesson_id, quiz_type);


--
-- Name: user_survey_responses user_survey_responses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_survey_responses
    ADD CONSTRAINT user_survey_responses_pkey PRIMARY KEY (response_id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: virtual_emails virtual_emails_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.virtual_emails
    ADD CONSTRAINT virtual_emails_pkey PRIMARY KEY (email_id);


--
-- Name: idx_learning_ai_tasks_user_mode_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_learning_ai_tasks_user_mode_status ON public.learning_ai_tasks USING btree (user_id, mode, status);


--
-- Name: active_accepted_challenges active_accepted_challenges_challenge_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.active_accepted_challenges
    ADD CONSTRAINT active_accepted_challenges_challenge_id_fkey FOREIGN KEY (challenge_id) REFERENCES public.multiplayer_challenges(challenge_id) ON DELETE CASCADE;


--
-- Name: active_accepted_challenges active_accepted_challenges_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.active_accepted_challenges
    ADD CONSTRAINT active_accepted_challenges_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: exercise_submissions exercise_submissions_exercise_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercise_submissions
    ADD CONSTRAINT exercise_submissions_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(exercise_id) ON DELETE CASCADE;


--
-- Name: exercise_submissions exercise_submissions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercise_submissions
    ADD CONSTRAINT exercise_submissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: exercises exercises_lesson_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercises
    ADD CONSTRAINT exercises_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(lesson_id) ON DELETE CASCADE;


--
-- Name: lesson_quizzes lesson_quizzes_lesson_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lesson_quizzes
    ADD CONSTRAINT lesson_quizzes_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(lesson_id) ON DELETE CASCADE;


--
-- Name: lesson_slides lesson_slides_lesson_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lesson_slides
    ADD CONSTRAINT lesson_slides_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(lesson_id) ON DELETE CASCADE;


--
-- Name: lessons lessons_module_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lessons
    ADD CONSTRAINT lessons_module_id_fkey FOREIGN KEY (module_id) REFERENCES public.modules(module_id) ON DELETE CASCADE;


--
-- Name: multiplayer_challenges multiplayer_challenges_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.multiplayer_challenges
    ADD CONSTRAINT multiplayer_challenges_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(user_id) ON DELETE SET NULL;


--
-- Name: multiplayer_submissions multiplayer_submissions_challenge_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.multiplayer_submissions
    ADD CONSTRAINT multiplayer_submissions_challenge_id_fkey FOREIGN KEY (challenge_id) REFERENCES public.multiplayer_challenges(challenge_id) ON DELETE CASCADE;


--
-- Name: multiplayer_submissions multiplayer_submissions_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.multiplayer_submissions
    ADD CONSTRAINT multiplayer_submissions_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.multiplayer_sessions(session_id) ON DELETE CASCADE;


--
-- Name: multiplayer_submissions multiplayer_submissions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.multiplayer_submissions
    ADD CONSTRAINT multiplayer_submissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: question_choices question_choices_question_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.question_choices
    ADD CONSTRAINT question_choices_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.quiz_questions(question_id) ON DELETE CASCADE;


--
-- Name: quiz_questions quiz_questions_quiz_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_questions
    ADD CONSTRAINT quiz_questions_quiz_id_fkey FOREIGN KEY (quiz_id) REFERENCES public.lesson_quizzes(quiz_id) ON DELETE CASCADE;


--
-- Name: session_players session_players_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session_players
    ADD CONSTRAINT session_players_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.multiplayer_sessions(session_id) ON DELETE CASCADE;


--
-- Name: session_players session_players_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session_players
    ADD CONSTRAINT session_players_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: survey_options survey_options_question_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.survey_options
    ADD CONSTRAINT survey_options_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.survey_questions(id) ON DELETE CASCADE;


--
-- Name: user_cosmetics user_cosmetics_cosmetic_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_cosmetics
    ADD CONSTRAINT user_cosmetics_cosmetic_id_fkey FOREIGN KEY (cosmetic_id) REFERENCES public.cosmetics(cosmetic_id) ON DELETE CASCADE;


--
-- Name: user_cosmetics user_cosmetics_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_cosmetics
    ADD CONSTRAINT user_cosmetics_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: user_mailbox user_mailbox_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_mailbox
    ADD CONSTRAINT user_mailbox_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: user_missions user_missions_email_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_missions
    ADD CONSTRAINT user_missions_email_id_fkey FOREIGN KEY (email_id) REFERENCES public.virtual_emails(email_id) ON DELETE CASCADE;


--
-- Name: user_missions user_missions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_missions
    ADD CONSTRAINT user_missions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: user_progress user_progress_lesson_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_progress
    ADD CONSTRAINT user_progress_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(lesson_id) ON DELETE CASCADE;


--
-- Name: user_progress user_progress_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_progress
    ADD CONSTRAINT user_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: user_quiz_attempts user_quiz_attempts_lesson_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_quiz_attempts
    ADD CONSTRAINT user_quiz_attempts_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES public.lessons(lesson_id) ON DELETE CASCADE;


--
-- Name: user_quiz_attempts user_quiz_attempts_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_quiz_attempts
    ADD CONSTRAINT user_quiz_attempts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: user_survey_responses user_survey_responses_question_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_survey_responses
    ADD CONSTRAINT user_survey_responses_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.survey_questions(id) ON DELETE CASCADE;


--
-- Name: user_survey_responses user_survey_responses_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_survey_responses
    ADD CONSTRAINT user_survey_responses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: virtual_emails virtual_emails_related_exercise_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.virtual_emails
    ADD CONSTRAINT virtual_emails_related_exercise_id_fkey FOREIGN KEY (related_exercise_id) REFERENCES public.exercises(exercise_id);


--
-- PostgreSQL database dump complete
--

\unrestrict qIvubUXJHCGtihtDnM3CxDNrAA3c6XQAtm6UkH7bVHFuLkjuVOBwymQn5RxcsRU

